---
- hosts: all
  connection: local
  gather_facts: no
  tasks:
    
    - name: Configure VRF
      ios_vrf:
        name: "{{ vrf_name }}"
        rd: 65001:{{ vrf_id }}
        route_both_ipv4:
          - 65001:{{ vrf_id }}
